---
- name: Check if google is installed
  command: dpkg-query -W google-chrome-stable
  register: google_check_deb
  failed_when: google_check_deb.rc > 1
  changed_when: google_check_deb.rc == 1

- name: Add Google Chrome key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  when: google_check_deb.rc == 1

- name: Add Google Chrome repo
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest=/etc/apt/sources.list.d/google-chrome.list owner=root group=root mode=644
  when: google_check_deb.rc == 1

- name: Update apt cache
  apt: update_cache=yes
  when: google_check_deb.rc == 1

- name: Install Google Chrome
  apt: name=google-chrome-stable state=present
  when: google_check_deb.rc == 1
