- name: Install packages
  apt: name={{ item }} state=present
  with_items:
  - git
  - kdiff3
- name: Set name for git
  sudo_user: "{{ ubuntu_login }}"
  command: git config --global user.name "{{ user_full_name }}"
- name: Set email for git
  sudo_user: "{{ ubuntu_login }}"
  command: git config --global user.email "{{ user_email }}"
- name: Set kdiff3 as mergetool
  sudo_user: "{{ ubuntu_login }}"
  command: git config --global merge.tool kdiff3
- name: Add a .netrc file to the home directory
  template: src=netrc dest=/home/{{ ubuntu_login }}/.netrc
