---
- include: git.yml
- name: Set the hostname
  hostname: name={{ hostname }}
- name: Install an edited bashrc
  copy: src=bashrc dest=/home/{{ ubuntu_login }}/.bashrc owner={{ ubuntu_login }} group={{ ubuntu_login }} mode=0644
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
  - vim
  - nodejs
  - nodejs-dbg
  - npm
  - virtualbox
  - jq
  - shutter
- include: vagrant.yml
- include: atom.yml
- include: chrome.yml
