---
- include: git.yml
- name: Set the hostname
  hostname: name={{ hostname }}
- name: Install an edited bashrc
  copy: src=bashrc dest=/home/{{ ubuntu_login }}/.bashrc owner={{ ubuntu_login }} group={{ ubuntu_login }} mode=0644
- name: Add some apt repositories
  apt_repository: repo={{ item }} state=present
  with_items:
  - 'ppa:chris-lea/node.js'
  - 'ppa:openjdk-r/ppa'
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
  - vim
  - nodejs
  - virtualbox
  - jq
  - shutter
  - openjdk-7-jdk
  - openjdk-8-jdk
- include: vagrant.yml
- include: atom.yml
- include: chrome.yml
