---
- include: git.yml
- name: Set the hostname
  hostname: name={{ hostname }}
- name: Install an edited bashrc
  copy: src=bashrc dest=/home/{{ user }}/.bashrc owner={{ user }} group={{ user }} mode=0644
- name: Install packages
  apt: name={{ item }} state=present
  with_items:
  - vim
  - nodejs
  - nodejs-dbg
  - npm
  - virtualbox
  - jq
- include: vagrant.yml
- include: atom.yml
