- name: Check if vagrant is installed
  command: dpkg-query -W vagrant
  register: vagrant_check_deb
  failed_when: vagrant_check_deb.rc > 1
  changed_when: vagrant_check_deb.rc == 1
- name: Download a recent Vagrant version
  get_url: url=https://dl.bintray.com/mitchellh/vagrant/{{ vagrant_package }} dest=/tmp/{{ vagrant_package }}
  when: vagrant_check_deb.rc == 1
- name: Install vagrant package
  apt: deb=/tmp/{{ vagrant_package }}
  when: vagrant_check_deb.rc == 1
